from enum import StrEnum


class JobStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PARSED = "PARSED"
    WAITING_TERM_REVIEW = "WAITING_TERM_REVIEW"
    WAITING_RISK_REVIEW = "WAITING_RISK_REVIEW"
    WAITING_CHAPTER_REVIEW = "WAITING_CHAPTER_REVIEW"
    TRANSLATING = "TRANSLATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ChunkStatus(StrEnum):
    PENDING = "PENDING"
    TRANSLATING = "TRANSLATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ChunkType(StrEnum):
    TEXT = "TEXT"
    TABLE = "TABLE"
    FORMULA = "FORMULA"
    PICTURE = "PICTURE"
    CODE = "CODE"


class RiskType(StrEnum):
    TABLE = "TABLE"
    FORMULA = "FORMULA"
    REFERENCE = "REFERENCE"
    STRUCTURE = "STRUCTURE"
    LONG_PARAGRAPH = "LONG_PARAGRAPH"
    PARSER_WARNING = "PARSER_WARNING"
    OMISSION = "OMISSION"
    TERMINOLOGY = "TERMINOLOGY"
    NUMBER_MISMATCH = "NUMBER_MISMATCH"
    FORMULA_MISMATCH = "FORMULA_MISMATCH"
    CITATION_MISMATCH = "CITATION_MISMATCH"
    INCOMPLETE_SENTENCE = "INCOMPLETE_SENTENCE"
    CROSS_PAGE_UNCERTAIN = "CROSS_PAGE_UNCERTAIN"
    SEMANTIC_DISCONTINUITY = "SEMANTIC_DISCONTINUITY"
    FORCED_TOKEN_SPLIT = "FORCED_TOKEN_SPLIT"
    OCR_TEXT_BREAK = "OCR_TEXT_BREAK"
    BOUNDARY_MODEL_FAILED = "BOUNDARY_MODEL_FAILED"


class ReviewType(StrEnum):
    HIGH_RISK_CHUNK = "HIGH_RISK_CHUNK"
    CHAPTER = "CHAPTER"


class ReviewStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
